aoc: samsung_heap: align the types of fd_flags and heap_flags (v6.11 compatibility)
Upstream commit [1] causes downstream pixel drivers to fail
for -Wincompatible-function-pointer-types.

aoc/ion_physical_heap.c:145:14: error: incompatible function pointer types initializing 'struct dma_buf *(*)(struct dma_heap *, unsigned long, u32, u64)' (aka 'struct dma_buf *(*)(struct dma_heap *, unsigned long, unsigned int, unsigned long long)') with an expression of type 'struct dma_buf *(struct dma_heap *, unsigned long, unsigned long, unsigned long)' [-Wincompatible-function-pointer-types]
  145 |         .allocate = ion_physical_heap_allocate,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Align the types. samsung_export_dmabuf(), the child method that uses
fd_flags, already gets updated in soc/gs/ in a previous soc/gs/ patch.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b9578c49456340ca4d3c7ddbaca054ffc2b51bc1 [1]
Test: TH
Bug: 359443502
Change-Id: If3fddbe254d509c0dfd5028eabcbfdfaf5fa0cbc
Signed-off-by: Tudor Ambarus <tudordana@google.com>