aoc/alsa: remove bespoke trigger DT parsing (v6.12 prep)
Linux commit [1] has removed bespoke trigger support and enum
snd_soc_dpcm_trigger::SND_SOC_DPCM_TRIGGER_BESPOKE is gone.

This causes this driver to fail compilation:
    .../alsa/aoc_alsa_card.c:1195:22: error: use of undeclared identifier 'SND_SOC_DPCM_TRIGGER_BESPOKE'
     1195 |                         dai->trigger[0] = SND_SOC_DPCM_TRIGGER_BESPOKE;
          |                                           ^
    ...alsa/aoc_alsa_card.c:1196:22: error: use of undeclared identifier 'SND_SOC_DPCM_TRIGGER_BESPOKE'
     1196 |                         dai->trigger[1] = SND_SOC_DPCM_TRIGGER_BESPOKE;
          |                                           ^
    2 errors generated.

None of the Pixel DTSs set the trigger property, so we can simply
remove those pieces from the code as this is unused.

Note: The code would probably (?) also have had to set struct
snd_soc_dai_ops::bespoke_trigger, because the core code uses this in
snd_soc_pcm_dai_bespoke_trigger(). So I am under the impression that
this isn't working anyway.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7d2fb3812acd [1]
      ("ASoC: remove bespoke trigger support")
Test: TH
Bug: 369296995
Change-Id: I7e23828868d88403a496c5cf5a0768895124e61f
Signed-off-by: André Draszik <draszik@google.com>